{{- if .Values.injector.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dragonfly.injector.fullname" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
    app: {{ template "dragonfly.name" . }}
    component: {{ .Values.injector.name }}
spec:
  replicas: {{ .Values.injector.replicas }}
  selector:
    matchLabels:
      app: {{ template "dragonfly.name" . }}
      component: {{ .Values.injector.name }}
  {{- if .Values.injector.updateStrategy }}
  strategy:
    {{- toYaml .Values.injector.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "dragonfly.name" . }}
        component: {{ .Values.injector.name }}
        {{- if .Values.injector.podLabels }}
        {{- toYaml .Values.injector.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.injector.podAnnotations }}
      annotations:
        {{- toYaml .Values.injector.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.injector.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.injector.tolerations }}
      tolerations:
        {{- toYaml .Values.injector.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.injector.affinity }}
      affinity:
        {{- toYaml .Values.injector.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.injector.priorityClassName }}
      priorityClassName: {{ .Values.injector.priorityClassName }}
      {{- end }}
      {{- with .Values.injector.image.pullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "dragonfly.injector.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: injector
          image: {{ include "injector.image" . }}
          imagePullPolicy: {{ .Values.injector.image.pullPolicy | quote }}
          command:
            - /opt/dragonfly/bin/injector
          args:
            - --health-probe-bind-address=:{{ .Values.injector.healthPort }}
            - --metrics-bind-address=:{{ .Values.injector.metricsPort }}
            - --metrics-secure={{ .Values.injector.metricsSecure }}
            - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
            - --webhook-cert-name=tls.crt
            - --webhook-cert-key=tls.key
            - --leader-elect={{ .Values.injector.leaderElection.enable }}
          ports:
            - name: webhook
              containerPort: {{ .Values.injector.webhookPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.injector.metricsPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.injector.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: {{ .Values.injector.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.injector.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.injector.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.injector.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: {{ .Values.injector.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.injector.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.injector.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.injector.readinessProbe.failureThreshold }}
          {{- if .Values.injector.resources }}
          resources:
            {{- toYaml .Values.injector.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            - name: config
              mountPath: /etc/dragonfly-injector
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: cert
          secret:
            secretName: {{ .Values.injector.certManager.secretName }}
            defaultMode: 420
        - name: config
          configMap:
            name: {{ template "dragonfly.injector.fullname" . }}-config
            defaultMode: 420
{{- end }}
