{{- if .Values.cdn.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.cdn.fullname" . }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.cdn.name }}
data:
  cdn.yaml: |-
    base:
      listenPort: {{ .Values.cdn.containerPort }}
      downloadPort: {{ .Values.cdn.nginxContiainerPort }}
      systemReservedBandwidth: {{ .Values.cdn.config.base.systemReservedBandwidth }}
      maxBandwidth: {{ .Values.cdn.config.base.maxBandwidth }}
      enableProfiler: {{ .Values.cdn.config.base.enableProfiler }}
      failAccessInterval: {{ .Values.cdn.config.base.failAccessInterval }}
      gcInitialDelay: {{ .Values.cdn.config.base.gcInitialDelay }}
      gcMetaInterval: {{ .Values.cdn.config.base.gcMetaInterval }}
      gcStorageInterval: {{ .Values.cdn.config.base.gcStorageInterval }}
      taskExpireTime: {{ .Values.cdn.config.base.taskExpireTime }}
      storagePattern: {{ .Values.cdn.config.base.storagePattern }}
      nodeSelector:
{{ toYaml .Values.cdn.nodeSelector | indent 8 }}
      manager:
        {{- if .Values.manager.enable }}
        addr: {{ template "dragonfly.manager.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.manager.grpcPort }}
        {{- else }}
        addr: {{ .Values.externalManager.host }}:{{ .Values.externalManager.grpcPort }}
        {{- end }}
        cdnClusterID: {{ .Values.cdn.config.base.manager.cdnClusterID }}
        keepAlive:
{{ toYaml .Values.cdn.config.base.manager.keepAlive | indent 10 }}
      console: {{ .Values.cdn.config.base.console }}
      {{- if .Values.cdn.metrics.enable }}
      metrics:
        addr: ":8000"
      {{- end }}
    {{- if .Values.cdn.config.jaeger }}
    jaeger: {{ .Values.cdn.config.jaeger }}
    {{- else if .Values.jaeger.enable }}
    jaeger: http://jaeger-all-in-one-collector.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }}:14268/api/traces
    {{- end }}
    manager:
      { { - if .Values.manager.enable } }
      addr: { { template "dragonfly.manager.fullname" . } }.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.manager.grpcPort }}
      {{- else }}
      addr: { { .Values.externalManager.host } }:{{ .Values.externalManager.grpcPort }}
      {{- end }}
      cdnClusterID: { { .Values.cdn.config.base.manager.cdnClusterID } }
      keepAlive:
{ { .Values.cdn.config.base.manager.keepAlive | indent 8 } }
    plugins:
{{ toYaml .Values.cdn.config.plugins | indent 6 }}
  nginx.conf: |-
    worker_rlimit_nofile        100000;

    events {
        use                     epoll;
        worker_connections      20480;
    }

    http {
        include                 mime.types;
        default_type            application/octet-stream;
        root                    /home/admin/cai/htdocs;
        sendfile                on;
        tcp_nopush              on;

        server_tokens           off;
        keepalive_timeout       5;

        client_header_timeout   1m;
        send_timeout            1m;
        client_max_body_size    3m;

        index                   index.html index.htm;
        access_log              on;
        log_not_found           on;

        gzip                    on;
        gzip_http_version       1.0;
        gzip_comp_level         6;
        gzip_min_length         1024;
        gzip_proxied            any;
        gzip_vary               on;
        gzip_disable            msie6;
        gzip_buffers            96 8k;
        gzip_types              text/xml text/plain text/css application/javascript application/x-javascript application/rss+xml application/json;

        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        Web-Server-Type nginx;
        proxy_set_header        WL-Proxy-Client-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect          off;
        proxy_buffers           128 8k;
        proxy_intercept_errors  on;

        server {
            listen              {{ .Values.cdn.nginxContiainerPort }};
            location / {
              root {{ (index .Values.cdn.config.plugins.storageDriver 0).config.baseDir }};
            }
        }
    }
{{- end }}
