{{- if .Values.jaeger.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/jaeger/jaeger-configmap.yaml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: jaeger-all-in-one
      app.kubernetes.io/name: jaeger-all-in-one
      app.kubernetes.io/part-of: jaeger
  strategy: {}
  template:
    metadata:
      labels:
        app: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: jaeger-all-in-one
        app.kubernetes.io/name: jaeger-all-in-one
        app.kubernetes.io/part-of: jaeger
    spec:
      containers:
      - args:
        - --query.ui-config=/etc/config/ui.json
        - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: jaegertracing/all-in-one:1.23.0
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 15
        name: jaeger
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
        - containerPort: 14267
          name: c-tchan-trft
        - containerPort: 14268
          name: c-binary-trft
        - containerPort: 16686
          name: query
        - containerPort: 14269
          name: admin-http
        - containerPort: 14250
          name: grpc
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: jaeger-all-in-one-ui-configuration-volume
          readOnly: true
        - mountPath: /etc/jaeger/sampling
          name: jaeger-all-in-one-sampling-configuration-volume
          readOnly: true
      serviceAccountName: jaeger-all-in-one
      volumes:
      - configMap:
          items:
          - key: ui
            path: ui.json
          name: jaeger-all-in-one-ui-configuration
        name: jaeger-all-in-one-ui-configuration-volume
      - configMap:
          items:
          - key: sampling
            path: sampling.json
          name: jaeger-all-in-one-sampling-configuration
        name: jaeger-all-in-one-sampling-configuration-volume
{{- end }}
